package hue.captains.singapura.js.homing.findash.trader;

import hue.captains.singapura.js.homing.core.Importable;
import hue.captains.singapura.js.homing.core.ModuleImports;
import hue.captains.singapura.js.homing.findash.core.css.FdControlCss;
import hue.captains.singapura.js.homing.findash.core.css.FdFrameCss;
import hue.captains.singapura.js.homing.findash.core.css.FdStatusCss;
import hue.captains.singapura.js.homing.findash.core.css.FdTextCss;
import hue.captains.singapura.js.homing.findash.core.kit.FinDashKitModule;
import hue.captains.singapura.js.homing.grid.RelationGridModule;
import hue.captains.singapura.js.homing.workspace.LifecycleHint;
import hue.captains.singapura.js.homing.workspace.WorkspaceWidget;

import java.util.List;

/**
 * The risk ladder — one pair's exposure down the tenor curve, on RFC 0050's
 * {@code RelationGrid}.
 *
 * <h2>Why one pair</h2>
 *
 * <p>A desk ladder normally reads pair → tenor with a subtotal per pair, and
 * {@code RelationGrid} has no row grouping: {@code GridViewMaps} takes a flat
 * list of primary keys, and {@code GridLayout.render} is given a row
 * <em>count</em>, not row headers. Rather than flatten every pair into
 * "EURUSD · 1W" keys and lose the grouping anyway, the ladder scopes itself to
 * the selected instrument and follows {@code InstrumentChanged} — which is how
 * the rest of this desk already works. With one pair on screen there is exactly
 * one subtotal, and it becomes an ordinary row (Σ) rather than a group header.
 * The limitation stops mattering instead of being worked around.</p>
 *
 * <h2>What each piece owns</h2>
 *
 * <ul>
 *   <li>The <b>adapter</b> is the seam onto the domain: it holds the rows for
 *       the current pair, answers {@code get(pk, column)}, and — because a cell
 *       never learns its row — makes the per-row judgements (is this reading
 *       stale? is this residual over its budget?) and ships them inside the
 *       value.</li>
 *   <li>The <b>cell</b> ({@link RiskLadderCellModule}) renders that judgement.</li>
 *   <li>The <b>grid</b> owns structure, selection, keyboard and copy — including
 *       TSV copy of a selected block, which is a real desk gesture.</li>
 * </ul>
 *
 * <p>Read-only by construction ({@code editable: false}): the ladder reports
 * risk the book already owns, and a UI is a consumer, not a calculator (P5).</p>
 */
public final class RiskLadderWidget
        extends WorkspaceWidget<WorkspaceWidget._None, RiskLadderWidget> {

    public static final RiskLadderWidget INSTANCE = new RiskLadderWidget();

    private RiskLadderWidget() {}

    private record construct() implements WorkspaceWidget._Construct<_None, RiskLadderWidget> {}

    @Override protected _Construct<_None, RiskLadderWidget> construct() { return new construct(); }
    @Override public Class<_None> paramsType() { return _None.class; }
    @Override public String title() { return "Risk Ladder"; }
    @Override public LifecycleHint lifecycleHint() { return LifecycleHint.MULTI; }

    @Override
    protected List<ModuleImports<? extends Importable>> bodyImports() {
        return List.of(
                new ModuleImports<>(List.of(new FinDashKitModule.fdk()),
                        FinDashKitModule.INSTANCE),
                new ModuleImports<>(List.of(new RelationGridModule.RelationGrid()),
                        RelationGridModule.INSTANCE),
                new ModuleImports<>(List.of(new RiskLadderCellModule.ladderCell()),
                        RiskLadderCellModule.INSTANCE),
                new ModuleImports<>(List.of(
                        new FdFrameCss.fd_cluster(),
                        new FdFrameCss.fd_header_row(),
                        new FdFrameCss.fd_scroll(),
                        new FdFrameCss.fd_section(),
                        new FdFrameCss.fd_widget_root()),
                        FdFrameCss.INSTANCE),
                new ModuleImports<>(List.of(
                        new FdTextCss.fd_caption(),
                        new FdTextCss.fd_muted(),
                        new FdTextCss.fd_title()),
                        FdTextCss.INSTANCE),
                new ModuleImports<>(List.of(
                        new FdStatusCss.fd_error_text()),
                        FdStatusCss.INSTANCE),
                new ModuleImports<>(List.of(
                        new FdControlCss.fd_btn_ghost()),
                        FdControlCss.INSTANCE));
    }

    @Override
    protected List<String> constructBodyJs() {
        return List.of(
            "    var root = branch.createElement('root', 'div');",
            "    css.setClass(root, fd_widget_root);",
            "",
            "    var head = fdk.el(branch, 'head', 'div', fd_header_row);",
            "    head.appendChild(fdk.el(branch, 'title-1', 'span', fd_title, 'RISK LADDER'));",
            "    var pairSlot = fdk.el(branch, 'pair', 'span', fd_cluster);",
            "    head.appendChild(pairSlot);",
            "    root.appendChild(head);",
            "    root.appendChild(fdk.el(branch, 'cap-1', 'div', [fd_caption, fd_muted],",
            "        'the book down the curve \\u00b7 a subtotal closes each pair, then the book \\u00b7 "
                    + "totals come from the desk, not from summing what you see (P5)'));",
            "",
            "    var host = fdk.el(branch, 'host', 'div', [fd_section, fd_scroll]);",
            "    root.appendChild(host);",
            "",
            "    var state = { focus: null, folded: {}, rows: [], byPk: {}, asOf: '' };",
            "    var grid = null, gridBranch = null;",
            "",
            "    // The columns, in the order a desk reads them: what it is, then the",
            "    // greeks, then how much to trust the numbers.",
            "    var COLUMNS = ['tenor', 'delta', 'vAtm', 'vRr', 'vBf', 'theta', 'fresh'];",
            "    var LABELS = { tenor: 'Book \\u25b8 tenor', delta: '\\u0394', vAtm: 'vATM',",
            "                   vRr: 'vRR', vBf: 'vBF', theta: '\\u0398', fresh: 'freshness' };",
            "",
            "    // ── ROW KINDS ────────────────────────────────────────────────────────",
            "    // A row is a pk, and what a pk MEANS is the domain's business, not the",
            "    // grid's. Three kinds, each with a scope:",
            "    //",
            "    //   leaf      one tenor of one pair          scope: that pair",
            "    //   subtotal  one pair, all tenors           scope: that pair",
            "    //   grand     the book                       scope: null (everything)",
            "    //",
            "    // The kind rides on the row record — never parsed back out of the pk",
            "    // string. A pk is an identity; asking it what sort of thing it is would",
            "    // be the same mistake as reading a machine field out of a display slot.",
            "    // The section row's identity is THE PAIR — a real domain entity, not a",
            "    // presentation row invented for the eye. That is what earns it a pk.",
            "    function section(pair)     { return { pk: pair, kind: 'section',",
            "                                          scope: pair, label: pair, data: {} }; }",
"    function leaf(pair, r)     { return { pk: pair + '/' + r.tenor, kind: 'leaf',",
            "                                          scope: pair, label: r.tenor, data: r }; }",
            "    // The subtotal does not repeat the pair: the header above already names",
            "    // it, and repeating it made the name the loudest thing in the block —",
            "    // read twice, needed once. A bare \\u03a3 was tried and read as a stray",
            "    // glyph in a column of words. The grand total names its scope because",
            "    // nothing above it declares one.",
            "    function subtotal(pair, r) { return { pk: pair + '/\\u03a3', kind: 'subtotal',",
            "                                          scope: pair, label: 'Subtotal', data: r }; }",
            "    function grand(r)          { return { pk: '\\u03a3\\u03a3', kind: 'grand',",
            "                                          scope: null, label: 'FXO book total', data: r }; }",
            "",
            "    function isAggregate(row) { return row.kind === 'subtotal' || row.kind === 'grand'; }",
            "    function isChrome(row)    { return row.kind !== 'leaf'; }   // exempt from value filters",
            "",
            "    // ORDER. Aggregates sort last WITHIN THEIR SCOPE — a pair's \\u03a3 closes",
            "    // its own block, the grand total closes the table. Last-overall would",
            "    // tear each subtotal away from the rows it totals, which reads as a",
            "    // mistake rather than a convention.",
            "    function order(d) {",
            "        var pairs = [], seen = {}, all = d.rows || [], i;",
            "        for (i = 0; i < all.length; i++) {",
            "            if (!seen[all[i].pair]) { seen[all[i].pair] = 1; pairs.push(all[i].pair); }",
            "        }",
            "        var out = [];",
            "        for (var p = 0; p < pairs.length; p++) {",
            "            var pair = pairs[p], sub = null;",
            "            out.push(section(pair));                 // opens its scope",
            "            for (i = 0; i < all.length; i++) {",
            "                if (all[i].pair !== pair) continue;",
            "                if (all[i].group) sub = all[i]; else out.push(leaf(pair, all[i]));",
            "            }",
            "            if (sub) out.push(subtotal(pair, sub));   // last within its scope",
            "        }",
            "        if (d.totals) out.push(grand(d.totals));      // last overall",
            "        return out;",
            "    }",
            "",
            "    // Every per-row judgement is made HERE, because a cell is never told",
            "    // which row it is in. The value carries the verdict — and the row kind,",
            "    // so the cell can render weight and refuse to be copied as data.",
            "    // A column the desk does not publish is still a CELL of its row: it must",
            "    // wear the row's band or the total reads as broken rather than partial.",
            "    // 'not published' is a value, not the absence of one — and the ladder",
            "    // will not sum the rows to fill the gap (P5).",
            "    function absent(rk) { return { kind: 'none', text: '\\u2014', rowKind: rk, agg: true }; }",
            "",
"    function cellValue(row, col) {",
            "        var r = row.data, agg = isAggregate(row);",
            "        // A section row has a name and nothing else. Every other column is",
            "        // VOID — not a missing measurement but no measurement at all — and the",
            "        // factory turns that into a different cell class entirely.",
            "        // The fold shows in the CARET and nowhere else \\u2014 the band keeps its",
            "        // face either way, so only the label needs to know.",
            "        if (row.kind === 'section') {",
            "            var open = !state.folded[row.scope];",
            "            return col === 'tenor'",
            "                ? { kind: 'label', text: (open ? '\\u25be ' : '\\u25b8 ') + row.label,",
            "                    agg: false, leaf: false, rowKind: 'section', scope: row.scope }",
            "                : { kind: 'void', rowKind: 'section', scope: row.scope };",
            "        }",
            "        // rowKind travels with EVERY value so each cell can wear the row's",
            "        // treatment — the grid owns the <tr>, so a band is drawn by its cells",
            "        // agreeing rather than by styling a row that is not ours.",
            "        var rk = row.kind;",
            "        if (col === 'tenor') {",
            "            // Everything under a header is indented under it \\u2014 the tenors AND",
            "            // the subtotal that closes them, on the same edge, so the closing",
            "            // row reads as part of the block. Only the grand total sits flush:",
            "            // nothing above it to belong to.",
            "            return { kind: 'label', text: row.label, agg: agg,",
            "                     indent: rk !== 'grand', rowKind: rk };",
            "        }",
            "        if (col === 'fresh') {",
            "            var secs = r.freshSecs;",
            "            if (secs == null) return absent(rk);",
            "            // The VERDICT comes from the desk (freshState, beside the number),",
            "            // not from a cut-off this widget invented. One function upstream",
            "            // judges every reading, so this column and the Risk Blotter's can",
            "            // never disagree about the same second (P5).",
            "            return { kind: 'fresh', n: secs, text: secs + 's', agg: agg, rowKind: rk,",
            "                     state: r.freshState };",
            "        }",
            "        var n = r[col];",
            "        if (n == null) return absent(rk);",
            "        // Reval budget is the desk's own trust metric: past it, the number",
            "        // on screen is Taylor-tracked rather than freshly revalued. The desk",
            "        // publishes the band (budgetState); the ladder relays it.",
            "        var st = r.budgetState || 'ok';",
            "        return { kind: 'num', n: n, text: fdk.fmt.compact(n), state: st, agg: agg,",
            "                 rowKind: rk };",
            "    }",
            "",
            "    // RelationAdapterContract. Every invariant the row kinds imply is",
            "    // enforced on THIS side — the grid needs to learn nothing about totals,",
            "    // because each seam it exposes (the filter predicate, the cell's copy",
            "    // value, these mutators) is already ours.",
            "    var adapter = {",
            "        pks:     function () { return state.rows.map(function (r) { return r.pk; }); },",
            "        columns: function () { return COLUMNS; },",
            "        get:     function (pk, col) {",
            "            var row = state.byPk[pk];",
            "            return row ? cellValue(row, col) : null;",
            "        },",
            "        subscribe:   function (fn) {},",
            "        unsubscribe: function (fn) {},",
            "        // An aggregate is derived, so it is not writable and not deletable —",
            "        // refused here rather than hoped about. (The ladder is read-only",
            "        // anyway; this is the invariant, not the current configuration.)",
            "        update:      function (pk, col, v) {",
            "            var row = state.byPk[pk];",
            "            if (!row || isAggregate(row)) return;",
            "        },",
            "        deleteRows:  function (pks) {}",
            "    };",
            "",
            "    // FILTERS. \"Never filtered out\" needs one refinement to be right: an",
            "    // aggregate is exempt from predicates over its MEMBERS' values, but it",
            "    // is still subject to choosing a scope. Filtering to EURUSD must drop",
            "    // the USDJPY subtotal — leaving it would show a total for rows that are",
            "    // not there. So: scope decides whether an aggregate appears at all,",
            "    // and value predicates never do.",
            "    // ONE predicate. Focus and folding are both view state, and filterRows",
            "    // holds a single raw filter — two calls would silently replace each",
            "    // other rather than compose.",
            "    function applyView() {",
            "        if (!grid) return;",
            "        grid.filterRows(function (pk) {",
            "            var row = state.byPk[pk];",
            "            if (!row) return false;",
            "            // The grand total spans every scope, so it survives both.",
            "            if (row.scope === null) return true;",
            "            if (state.focus && row.scope !== state.focus) return false;",
            "            // Folding hides the DETAIL and keeps the summary — that is the",
            "            // point of folding a block rather than removing it.",
            "            if (row.kind === 'leaf' && state.folded[row.scope]) return false;",
            "            return true;",
            "        });",
            "    }",
            "",
            "    function toggleSection(scope) {",
            "        if (!scope) return;",
            "        state.folded[scope] = !state.folded[scope];",
            "        applyView();",
            "        // Repaint the caret through the grid's own direct-update path rather",
            "        // than rebuilding: the row is unchanged, only its disclosure is.",
            "        var row = state.byPk[scope];",
            "        if (row && grid) {",
            "            grid.updateCell(scope, 'tenor', cellValue(row, 'tenor'));",
            "            // updateCell batches on requestAnimationFrame. A fold is a direct",
            "            // answer to a gesture, so it should not wait on the compositor —",
            "            // and rAF does not run at all in a hidden tab, which would leave",
            "            // the caret pointing the wrong way until the pane came forward.",
            "            grid.flushNow();",
            "        }",
            "    }",
            "",
            "    // The chip strip is rebuilt whenever the pair changes, so it owns a",
            "    // dissolvable sub-branch: dissolve() releases the elements AND their",
            "    // names, which is what makes a re-render safe.",
            "    var pairBranch = null;",
            "",
            "    // Enter folds the section under the cursor — the keyboard equivalent of",
            "    // the double-click, so the ladder can be driven without a mouse. The grid",
            "    // leaves Enter alone (its own keydown routes to the edit controller, inert",
            "    // while editable is false) and it tells us where the cursor sits, so this",
            "    // needs no cooperation from it.",
            "    //",
            "    // Bound through setActive rather than to the grid's element: under RFC",
            "    // 0048 the ENTERED PANE holds DOM focus, so a listener hung on our own",
            "    // container would never see the key. Same contract the trade blotter's",
            "    // arrow keys keep.",
            "    var keyHandler = function (ev) {",
            "        if (ev.key !== 'Enter' || !grid) return;",
            "        var tag = ev.target && ev.target.tagName;",
            "        if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return;",
            "        var at = null;",
            "        try { at = JSON.parse(grid.cursor()); } catch (e) { return; }",
            "        if (!at || !at.pk) return;",
            "        var row = state.byPk[at.pk];",
            "        if (!row || row.kind !== 'section') return;",
            "        toggleSection(row.scope);",
            "        ev.preventDefault();",
            "    };",
            "",
            "    function renderPairChip() {",
            "        if (pairBranch) pairBranch.dissolve();",
            "        pairBranch = branch.createBranch('pair-strip');",
            "        pairBranch.activate(pairSlot);",
            "        if (state.focus) {",
            "            pairSlot.appendChild(fdk.chip(pairBranch, 'pair-chip', 'neutral', state.focus));",
            "            var clear = fdk.el(pairBranch, 'clear', 'button', fd_btn_ghost, 'whole book');",
            "            clear.onclick = function () { state.focus = null; renderPairChip(); applyView(); };",
            "            pairSlot.appendChild(clear);",
            "        } else {",
            "            pairSlot.appendChild(fdk.chip(pairBranch, 'pair-chip', 'neutral', 'whole book'));",
            "        }",
            "        if (state.asOf) {",
            "            pairSlot.appendChild(fdk.el(pairBranch, 'asof', 'span', [fd_caption, fd_muted],",
            "                'as-of ' + state.asOf));",
            "        }",
            "    }",
            "",
            "    function build() {",
            "        // The grid owns its cells' elements, so it gets a branch of its own",
            "        // that is dissolved whole when the pair changes — the same discipline",
            "        // every re-rendering region here follows.",
            "        if (grid) { grid.destroy(); grid = null; }",
            "        if (gridBranch) gridBranch.dissolve();",
            "        gridBranch = branch.createBranch('grid');",
            "        gridBranch.activate(host);",
            "        renderPairChip();",
            "        if (!state.rows.length) {",
            "            host.appendChild(fdk.el(gridBranch, 'empty', 'div', [fd_caption, fd_muted],",
            "                'no risk rows'));",
            "            return;",
            "        }",
            "        grid = new RelationGrid({",
            "            container:   host,",
            "            branch:      gridBranch,",
            "            adapter:     adapter,",
            "            cellFactory: function (col, value, meta) {",
            "                return ladderCell(col, value, { onToggleSection: toggleSection });",
            "            },",
            "            editable:    false,",
            "            header:      { show: true, sticky: true, includeInCopy: true, labels: LABELS }",
            "        });",
            "        applyView();",
            "    }",
            "",
            "    function load() {",
            "        fdk.load('/fx/book', { branch: branch, host: host, what: 'risk ladder' }, function (d) {",
            "                state.asOf = d.slice ? 'slice ' + d.slice : '';",
            "                state.rows = order(d);",
            "                state.byPk = {};",
            "                for (var i = 0; i < state.rows.length; i++) {",
            "                    state.byPk[state.rows[i].pk] = state.rows[i];",
            "                }",
            "                build();",
            "        });",
            "    }",
            "",
            "    var party = (workspaceCtx && workspaceCtx.deskParty) ? workspaceCtx.deskParty : null;",
            "    var actorId = null;",
            "    if (party) {",
            "        actorId = fdk.actorId('trader/ladder', branch);",
            "        party.joinActor({",
            "            id: actorId,",
            "            parentSecretary: 'desk',",
            "            reactors: {",
            "                InstrumentChanged: function (msg) {",
            "                    var ins = msg.instrument || {};",
            "                    if (!ins.pair || ins.pair === state.focus) return;",
            "                    // A pair selection FOCUSES the ladder rather than reloading",
            "                    // it: the whole book stays loaded and the filter narrows the",
            "                    // view, so the grand total keeps spanning what it always",
            "                    // spanned and 'whole book' is one click back.",
            "                    state.focus = ins.pair;",
            "                    renderPairChip();",
            "                    applyView();",
            "                }",
            "            }",
            "        });",
            "        party.tellFrom(actorId, { kind: 'CurrentInstrumentRequested' });",
            "    }",
            "",
            "    load();",
            "",
            "    return {",
            "        root: root,",
            "        setActive: function (active) {",
            "            if (active) document.addEventListener('keydown', keyHandler);",
            "            else        document.removeEventListener('keydown', keyHandler);",
            "        },",
            "        partyDeregister: function () {",
            "            document.removeEventListener('keydown', keyHandler);",
            "            if (grid) { grid.destroy(); }",
            "            if (actorId && party) { party.leave(actorId); }",
            "        }",
            "    };");
    }
}
