package hue.captains.singapura.js.homing.findash.book;

import hue.captains.singapura.js.homing.core.Importable;
import hue.captains.singapura.js.homing.core.ModuleImports;
import hue.captains.singapura.js.homing.findash.core.kit.FinDashKitModule;
import hue.captains.singapura.js.homing.workspace.LifecycleHint;
import hue.captains.singapura.js.homing.workspace.WorkspaceWidget;
import hue.captains.singapura.js.homing.findash.core.css.FdFrameCss;
import hue.captains.singapura.js.homing.findash.core.css.FdStatusCss;
import hue.captains.singapura.js.homing.findash.core.css.FdTextCss;
import hue.captains.singapura.js.homing.findash.core.css.FdControlCss;
import hue.captains.singapura.js.homing.findash.core.css.FdSurfaceCss;

import java.util.List;

/**
 * The Trade Blotter — the trade-journal anchor shared across workspaces
 * (middle office, trader, product control, audit): the journal rendered as a
 * blotter (study §10 — the journal IS the audit trail; the UI just renders
 * it). Every trade carries the slice it was priced on (P1), and amended
 * trades unfold their full journaled amendment history (who, what, P&amp;L
 * impact, four-eyes). Follows {@code InstrumentChanged} (filters by pair) and
 * drives — clicking a trade broadcasts its pair.
 *
 * <p><b>Aggregated view:</b> when the portfolio selection spans more than one
 * leaf (a book or the desk root), the blotter switches to per-portfolio
 * groups — a Σ header with trade count and net PV at booking, then each
 * child portfolio with its own subtotal. A leaf selection keeps the flat
 * journal. Presentation-only arithmetic (sorting/bucketing per P5).</p>
 */
public final class TradeBlotterWidget
        extends WorkspaceWidget<WorkspaceWidget._None, TradeBlotterWidget> {

    public static final TradeBlotterWidget INSTANCE = new TradeBlotterWidget();

    private TradeBlotterWidget() {}

    private record construct() implements WorkspaceWidget._Construct<_None, TradeBlotterWidget> {}

    @Override protected _Construct<_None, TradeBlotterWidget> construct() { return new construct(); }
    @Override public Class<_None> paramsType() { return _None.class; }
    @Override public String title() { return "Trade Blotter"; }
    @Override public LifecycleHint lifecycleHint() { return LifecycleHint.MULTI; }

    @Override
    protected List<ModuleImports<? extends Importable>> bodyImports() {
        // One entry per CssGroup: ImportsFor is keyed on the source module, so a
        // second entry for the same group replaces the first rather than adding
        // to it — split entries would silently drop the earlier classes.
        return List.of(
                new ModuleImports<>(List.of(new FinDashKitModule.fdk()),
                        FinDashKitModule.INSTANCE),
                // The row is TradeRowModule's job; the classes it needs are
                // declared there, which is why they are gone from below.
                new ModuleImports<>(List.of(new TradeRowModule.tradeRow()),
                        TradeRowModule.INSTANCE),
                new ModuleImports<>(List.of(
                        new FdFrameCss.fd_cluster(),
                        new FdFrameCss.fd_header_row(),
                        new FdFrameCss.fd_row(),
                        new FdFrameCss.fd_section(),
                        new FdFrameCss.fd_widget_root()),
                        FdFrameCss.INSTANCE),
                new ModuleImports<>(List.of(
                        new FdTextCss.fd_caption(),
                        new FdTextCss.fd_muted(),
                        new FdTextCss.fd_num(),
                        new FdTextCss.fd_strong(),
                        new FdTextCss.fd_strongest(),
                        new FdTextCss.fd_title()),
                        FdTextCss.INSTANCE),
                new ModuleImports<>(List.of(
                        new FdStatusCss.fd_error_text()),
                        FdStatusCss.INSTANCE),
                new ModuleImports<>(List.of(
                        new FdControlCss.fd_btn_ghost()),
                        FdControlCss.INSTANCE),
                new ModuleImports<>(List.of(
                        new FdSurfaceCss.fd_panel(),
                        new FdSurfaceCss.fd_rule_strong()),
                        FdSurfaceCss.INSTANCE));
    }

    @Override
    protected List<String> constructBodyJs() {
        return List.of(
            "    var root = branch.createElement('root', 'div');",
            "    css.setClass(root, fd_widget_root);",
            "",
            "    var state = { all: [], filter: null, portfolio: null, open: {}, pfIndex: {},",
            "                  selectedId: null };",
            "",
            "    // PV-at-booking strings are uniform EUR ('+\\u20ac142,399' / '\\u2212\\u20ac9,100') —",
            "    // parse for presentation-only subtotals (bucketing for display, P5).",
            "    function parsePv(s) {",
            "        var neg = s.indexOf('\\u2212') >= 0 || s.indexOf('-') >= 0;",
            "        var v = parseInt(String(s).replace(/[^0-9]/g, '') || '0', 10);",
            "        return neg ? -v : v;",
            "    }",
            "    function fmtPv(v) {",
            "        return (v < 0 ? '\\u2212' : '+') + '\\u20ac' + fdk.fmt.amount(Math.abs(v));",
            "    }",
            "",
            "    // Both the filter strip and the journal list are rebuilt on every",
            "    // selection change. A branch element name is unique for the branch's",
            "    // life, so each region owns a sub-branch that is dissolved and",
            "    // re-created per render — dissolve() detaches the elements too, which",
            "    // is what retires the old clear() loops.",
            "    var filterBranch = null, listBranch = null;",
            "",
            "    // Set while drawing, read once the list is built: arrowing past the",
            "    // bottom of the pane has to bring the row with it, or the selection",
            "    // walks off screen and the desk loses its place.",
            "    var selectedEl = null;",
            "    function reveal() {",
            "        if (selectedEl && selectedEl.scrollIntoView) {",
            "            selectedEl.scrollIntoView({ block: 'nearest' });",
            "        }",
            "    }",
            "",
            "    var head = fdk.el(branch, 'head', 'div', fd_header_row);",
            "    head.appendChild(fdk.el(branch, 'title-1', 'span', fd_title, ",
            "        'TRADE BLOTTER'));",
            "    head.appendChild(fdk.el(branch, 'cap-1', 'span', fd_caption, ",
            "        'the journal, rendered \\u00b7 amendments unfold \\u00b7 \\u2191\\u2193 to move'));",
            "    var filterSlot = fdk.el(branch, 'cluster-1', 'span', fd_cluster);",
            "    head.appendChild(filterSlot);",
            "    root.appendChild(head);",
            "",
            "    var list = fdk.el(branch, 'sect-1', 'div', fd_section);",
            "    root.appendChild(list);",
            "",
            "    var party = (workspaceCtx && workspaceCtx.deskParty) ? workspaceCtx.deskParty : null;",
            "    var actorId = null;",
            "    // The trade bus is optional: a workspace that shows the blotter without",
            "    // any trade-level consumer need not declare it.",
            "    var tradeParty = (workspaceCtx && workspaceCtx.tradeParty) ? workspaceCtx.tradeParty : null;",
            "    var tradeActorId = null;",
            "",
            "    function renderFilter() {",
            "        if (filterBranch) filterBranch.dissolve();",
            "        filterBranch = branch.createBranch('filter');",
            "        filterBranch.activate(root);",
            "        if (!state.filter && !state.portfolio) return;",
            "        if (state.portfolio) {",
            "            filterSlot.appendChild(fdk.chip(filterBranch, 'pf', 'neutral',",
            "                '\\ud83d\\udcc1 ' + state.portfolio.label));",
            "        }",
            "        if (state.filter) {",
            "            filterSlot.appendChild(fdk.chip(filterBranch, 'ins', 'neutral', state.filter));",
            "        }",
            "        var x = fdk.el(filterBranch, 'clear', 'button', fd_btn_ghost, 'clear');",
            "        x.onclick = function () { state.filter = null; state.portfolio = null; render(); };",
            "        filterSlot.appendChild(x);",
            "    }",
            "",
            "    // k is the row's unique key within this render pass. The row itself is",
            "    // TradeRowModule's business; what the blotter adds is which trade is",
            "    // selected, so it can hold on to that element for reveal().",
            "    function row(b, k, t) {",
            "        var selected = state.selectedId === t.id;",
            "        var el = tradeRow({ branch: b, key: k, trade: t,",
            "            open: !!state.open[t.id], selected: selected, onSelect: selectTrade });",
            "        if (selected) selectedEl = el;",
            "        return el;",
            "    }",
            "",
            "    function visibleTrades() {",
            "        var out = [];",
            "        for (var i = 0; i < state.all.length; i++) {",
            "            var t = state.all[i];",
            "            if (state.portfolio && state.portfolio.leafIds.indexOf(t.portfolioId) < 0) continue;",
            "            if (state.filter && t.pair !== state.filter) continue;",
            "            out.push(t);",
            "        }",
            "        return out;",
            "    }",
            "",
            "    // A non-leaf selection groups the journal by child portfolio. Both the",
            "    // renderer and the arrow keys read the grouping from here, so the order",
            "    // the eye sees and the order the arrows follow cannot drift apart.",
            "    function aggregated() {",
            "        return state.portfolio && state.portfolio.leafIds.length > 1;",
            "    }",
            "",
            "    function groupedTrades() {",
            "        var shown = visibleTrades(), out = [], leafIds = state.portfolio.leafIds;",
            "        for (var l = 0; l < leafIds.length; l++) {",
            "            var g = [];",
            "            for (var i = 0; i < shown.length; i++) {",
            "                if (shown[i].portfolioId === leafIds[l]) g.push(shown[i]);",
            "            }",
            "            if (g.length) out.push({ leafId: leafIds[l], trades: g });",
            "        }",
            "        return out;",
            "    }",
            "",
            "    /** Every visible trade, flattened into the order it is drawn. */",
            "    function orderedTrades() {",
            "        if (!aggregated()) return visibleTrades();",
            "        var gs = groupedTrades(), out = [];",
            "        for (var i = 0; i < gs.length; i++) out = out.concat(gs[i].trades);",
            "        return out;",
            "    }",
            "",
            "    // The one path a selection takes, whichever way it was made. `unfold`",
            "    // is the click's extra: pointing at an amended trade opens its history.",
            "    // Arrow keys move without unfolding — travel should not mutate.",
            "    function selectTrade(t, unfold) {",
            "        if (unfold && t.amendments.length) state.open[t.id] = !state.open[t.id];",
            "        state.selectedId = t.id;",
            "        // Two statements, two scopes. The TRADE goes on the trade bus — that",
            "        // is the drill-down the lifecycle view follows. The INSTRUMENT goes",
            "        // on the desk bus because a trade genuinely does identify one, and",
            "        // the pricer and surface manager should follow. Previously the trade",
            "        // rode inside the instrument message as a `ref`, which every consumer",
            "        // then had to filter back out.",
            "        if (tradeParty && tradeActorId) {",
            "            tradeParty.tellFrom(tradeActorId, { kind: 'TradeSelected', trade: t });",
            "        }",
            "        if (party && actorId) {",
            "            party.tellFrom(actorId, { kind: 'InstrumentSelected',",
            "                instrument: { pair: t.pair } });",
            "        }",
            "        render();",
            "    }",
            "",
            "    // Arrows walk the journal while this tab is the active one — the same",
            "    // contract the portfolio tree keeps, so two open blotters never both",
            "    // answer one keypress. A focused text box keeps its own arrow keys.",
            "    var keyHandler = function (ev) {",
            "        if (ev.key !== 'ArrowDown' && ev.key !== 'ArrowUp') return;",
            "        var tag = ev.target && ev.target.tagName;",
            "        if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT') return;",
            "        var rows = orderedTrades();",
            "        if (!rows.length) return;",
            "        var at = -1;",
            "        for (var i = 0; i < rows.length; i++) {",
            "            if (rows[i].id === state.selectedId) { at = i; break; }",
            "        }",
            "        var next;",
            "        if (at < 0) {",
            "            // Nothing picked yet: the first press lands on the end you came from.",
            "            next = ev.key === 'ArrowDown' ? rows[0] : rows[rows.length - 1];",
            "        } else {",
            "            var to = at + (ev.key === 'ArrowDown' ? 1 : -1);",
            "            if (to < 0 || to >= rows.length) { ev.preventDefault(); return; }",
            "            next = rows[to];",
            "        }",
            "        selectTrade(next, false);",
            "        ev.preventDefault();",
            "    };",
            "",
            "    function render() {",
            "        renderFilter();",
            "        if (listBranch) listBranch.dissolve();",
            "        listBranch = branch.createBranch('journal');",
            "        listBranch.activate(root);",
            "        var b = listBranch;",
            "        selectedEl = null;",
            "        var shown = visibleTrades();",
            "        if (!shown.length) {",
            "            list.appendChild(fdk.el(b, 'empty', 'div', [fd_caption, fd_muted],",
            "                'no trades for this filter'));",
            "            return;",
            "        }",
            "        if (!aggregated()) {",
            "            for (var i = 0; i < shown.length; i++) list.appendChild(row(b, i, shown[i]));",
            "            reveal();",
            "            return;",
            "        }",
            "        var net = 0;",
            "        for (i = 0; i < shown.length; i++) net += parsePv(shown[i].pvAtBooking);",
            "        var total = fdk.el(b, 'total', 'div', [fd_panel, fd_row]);",
            "        total.appendChild(fdk.el(b, 'total-label', 'span', fd_strongest,",
            "            '\\u03a3 ' + state.portfolio.label));",
            "        total.appendChild(fdk.el(b, 'total-count', 'span', null,",
            "            shown.length + (shown.length === 1 ? ' trade' : ' trades')));",
            "        total.appendChild(fdk.el(b, 'total-pv', 'span', [fd_strong, fd_num],",
            "            'net PV at booking ' + fmtPv(net)));",
            "        total.appendChild(fdk.el(b, 'total-note', 'span', [fd_caption, fd_muted],",
            "            'presentation-only aggregation (P5)'));",
            "        list.appendChild(total);",
            "",
            "        var gs = groupedTrades();",
            "        for (var l = 0; l < gs.length; l++) {",
            "            var group = gs[l].trades;",
            "            var sub = 0;",
            "            for (i = 0; i < group.length; i++) sub += parsePv(group[i].pvAtBooking);",
            "            var meta = state.pfIndex[gs[l].leafId];",
            "            var gh = fdk.el(b, 'g-' + l, 'div', [fd_row, fd_rule_strong]);",
            "            gh.appendChild(fdk.el(b, 'g-label-' + l, 'span', fd_strongest,",
            "                '\\u25b8 ' + (meta ? meta.label : gs[l].leafId)));",
            "            gh.appendChild(fdk.el(b, 'g-count-' + l, 'span', null,",
            "                group.length + (group.length === 1 ? ' trade' : ' trades')));",
            "            gh.appendChild(fdk.el(b, 'g-pv-' + l, 'span', fd_num, fmtPv(sub)));",
            "            list.appendChild(gh);",
            "            // key the rows by group so two groups' rows never collide",
            "            for (i = 0; i < group.length; i++) {",
            "                list.appendChild(row(b, l + '-' + i, group[i]));",
            "            }",
            "        }",
            "        reveal();",
            "    }",
            "",
            "    if (party) {",
            "        actorId = fdk.actorId('book/trades', branch);",
            "        party.joinActor({",
            "            id: actorId,",
            "            parentSecretary: 'desk',",
            "            reactors: {",
            "                InstrumentChanged: function (msg) {",
            "                    var ins = msg.instrument || {};",
            "                    if (!ins.pair) return;",
            "                    // Picking a trade publishes its pair for the pricer and the",
            "                    // surface manager, and that broadcast comes straight back",
            "                    // here. Narrowing on our own echo would collapse the journal",
            "                    // under the cursor the moment an arrow moved off the current",
            "                    // pair — you could never travel out of the pair you landed",
            "                    // on. A pair chosen anywhere else still filters, as before.",
            "                    if (msg.by && msg.by === actorId) return;",
            "                    state.filter = ins.pair;",
            "                    render();",
            "                },",
            "                PortfolioChanged: function (msg) {",
            "                    var pf = msg.portfolio || {};",
            "                    if (!pf.leafIds) return;",
            "                    state.portfolio = pf;",
            "                    // A new scope invalidates the trade picked inside the old one.",
            "                    state.selectedId = null;",
            "                    if (tradeParty && tradeActorId) {",
            "                        tradeParty.tellFrom(tradeActorId, { kind: 'TradeCleared' });",
            "                    }",
            "                    render();",
            "                }",
            "            }",
            "        });",
            "        party.tellFrom(actorId, { kind: 'CurrentPortfolioRequested' });",
            "    }",
            "",
            "    if (tradeParty) {",
            "        // Join to publish. The blotter is the source of trade selections and",
            "        // has no reactor of its own — it already knows what it picked.",
            "        tradeActorId = fdk.actorId('book/trades-sel', branch);",
            "        tradeParty.joinActor({ id: tradeActorId, parentSecretary: 'trade', reactors: {} });",
            "    }",
            "",
            "    Promise.all([",
            "        fetch('/fx/trades').then(function (r) {",
            "            if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); }),",
            "        fetch('/fx/portfolios').then(function (r) {",
            "            if (!r.ok) throw new Error('HTTP ' + r.status); return r.json(); })",
            "    ]).then(function (res) {",
            "        state.all = res[0].trades;",
            "        state.pfIndex = res[1].index;   // id -> {label, leafIds} for group headers",
            "        render();",
            "    }).catch(function (e) {",
            "        list.appendChild(fdk.el(branch, 'err-1', 'div', fd_error_text, ",
            "            'trades load failed: ' + (e && e.message ? e.message : e)));",
            "    });",
            "",
            "    return {",
            "        root: root,",
            "        setActive: function (active) {",
            "            if (active) document.addEventListener('keydown', keyHandler);",
            "            else        document.removeEventListener('keydown', keyHandler);",
            "        },",
            "        partyDeregister: function () {",
            "            document.removeEventListener('keydown', keyHandler);",
            "            if (actorId && party) { party.leave(actorId); }",
            "            if (tradeActorId && tradeParty) { tradeParty.leave(tradeActorId); }",
            "        }",
            "    };");
    }
}
